name: karlo petigny music corporation
favicon: null
layout_spectrum: 0.9636345081962645
typography_spectrum: 0.4739327230490744
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.25872523756697774
  lightness: 0.5905654481612146
  saturation: 0.3916937727481127
  rhythmicContrast: 0.5729552032426
purpose: []
